serenity.project.name=PageObjectPattern
drivers.windows.webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe
webdriver.driver=chrome
report.customfields.ApplicationVersion = 1.0.0
report.customfields.RunDate=27.08.2020
